app/alerts/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from app.extensions import db
from app.models.alert_config import AlertConfig
import json
from app.models.alert_action import AlertAction 
from app.models.log_entry import LogEntry

alert_bp = Blueprint("alerts", __name__, url_prefix="/alerts")

@alert_bp.route("/")
@login_required
def list_alerts():
    """
    Admin → sees all alerts
    User  → sees only their alerts
    """
    if current_user.role == "admin":
        alerts = AlertConfig.query.order_by(AlertConfig.id.desc()).all()
    else:
        alerts = AlertConfig.query.filter_by(
            user_id=current_user.id
        ).order_by(AlertConfig.id.desc()).all()

    return render_template("alert_list.html", alerts=alerts)


@alert_bp.route("/toggle/<int:alert_id>")
@login_required
def toggle_alert(alert_id):
    alert = AlertConfig.query.get_or_404(alert_id)

    # Users can toggle only their own alerts
    if current_user.role != "admin" and alert.user_id != current_user.id:
        return "Unauthorized", 403

    alert.enabled = not alert.enabled
    db.session.commit()

    return redirect(url_for("alerts.list_alerts"))

@alert_bp.route("/edit/<int:alert_id>", methods=["GET", "POST"])
@login_required
def edit_alert(alert_id):
    alert = AlertConfig.query.get_or_404(alert_id)

    # Security: user can edit only own alerts (admin can edit all)
    if current_user.role != "admin" and alert.user_id != current_user.id:
        return "Unauthorized", 403

    email_action = AlertAction.query.filter_by(
        alert_id=alert.id, action_type="email"
    ).first()

    sn_action = AlertAction.query.filter_by(
        alert_id=alert.id, action_type="servicenow"
    ).first()

    if request.method == "POST":
        alert.name = request.form["name"]
        alert.keyword = request.form["keyword"]
        alert.interval_minutes = int(request.form["interval_minutes"])
        alert.enabled = "enabled" in request.form

        if "email_action" in request.form:
            email_config = {
                "to": request.form.get("email_to", "").split(","),
                "subject": request.form.get("email_subject"),
                "body": request.form.get("email_body"),
                "importance": request.form.get("email_importance", "normal"),
                "include_log": "email_include_log" in request.form,
            }

            if email_action:
                email_action.config = email_config
            else:
                db.session.add(AlertAction(
                    alert_id=alert.id,
                    action_type="email",
                    config=email_config
                ))
        else:
            if email_action:
                db.session.delete(email_action)

        # ---- SERVICENOW ACTION ----
        if "sn_action" in request.form:
            sn_config = {
                "priority": request.form.get("sn_priority"),
                "short_description": request.form.get("sn_short_desc"),
                "description": request.form.get("sn_description"),
                "include_log": "sn_include_log" in request.form,
            }

            if sn_action:
                sn_action.config = sn_config
            else:
                db.session.add(AlertAction(
                    alert_id=alert.id,
                    action_type="servicenow",
                    config=sn_config
                ))
        else:
            if sn_action:
                db.session.delete(sn_action)


        db.session.commit()
        flash("Alert updated successfully", "success")
        return redirect(url_for("alerts.list_alerts"))

    return render_template("edit_alert.html", alert=alert,email_action=email_action, sn_action=sn_action)

@alert_bp.route("/create", methods=["GET", "POST"])
@login_required
def create_alert():
    if request.method == "POST":
        keyword = request.form["keyword"].strip()

        # Get multiple actions
        email_selected = "email_action" in request.form
        sn_selected = "sn_action" in request.form

        if not email_selected and not sn_selected:
            return "At least one action must be selected", 400

        alert = AlertConfig(
            name=request.form["name"],
            keyword=request.form["keyword"],
            user_id=current_user.id,
            interval_minutes=int(request.form["interval_minutes"]),
        )
        db.session.add(alert)
        db.session.flush()  # get alert.id

        # Email action
        if "email_action" in request.form:
            email_config = {
                "to": request.form["email_to"].split(","),
                "subject": request.form["email_subject"],
                "body": request.form["email_body"],
                "importance": request.form["email_importance"],
                "throttle_minutes": int(request.form["email_throttle"] or 0),
                "include_log": "email_include_log" in request.form,
            }

            db.session.add(AlertAction(
                alert_id=alert.id,
                action_type="email",
                config=email_config
            ))

        # ServiceNow action
        if "sn_action" in request.form:
            sn_config = {
                "priority": request.form["sn_priority"],
                "short_description": request.form["sn_short_desc"],
                "description": request.form["sn_description"],
                "throttle_minutes": int(request.form["sn_throttle"] or 0),
                "include_log": "email_include_log" in request.form,
            }

            db.session.add(AlertAction(
                alert_id=alert.id,
                action_type="servicenow",
                config=sn_config
            ))

        db.session.commit()

        return redirect(url_for("alerts.list_alerts"))

    return render_template("create_alert.html")

app/logs/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required
from app.utils.decorators import admin_required
from .parser import parse_log_file
from app.models.log_source import LogSource
from app.extensions import db
from app.models.log_entry import LogEntry


log_bp = Blueprint("logs", __name__, url_prefix="/logs")

# Admin only
@log_bp.route("/add-source", methods=["GET", "POST"])
@login_required
@admin_required
def add_log_source():
    if request.method == "POST":
        name = request.form["name"]
        file_path = request.form["file_path"]

        source = LogSource(
            name=name,
            file_path=file_path
        )
        db.session.add(source)
        db.session.commit()

        flash("Log source added successfully", "success")
        return redirect(url_for("logs.add_log_source"))

    return render_template("add_log_source.html")


@log_bp.route("/sources")
@login_required
@admin_required
def list_log_sources():
    sources = LogSource.query.order_by(LogSource.id.desc()).all()
    return render_template("log_sources.html", sources=sources)


@log_bp.route("/sources/toggle/<int:source_id>")
@login_required
@admin_required
def toggle_log_source(source_id):
    source = LogSource.query.get_or_404(source_id)
    source.enabled = not source.enabled
    db.session.commit()
    return redirect(url_for("logs.list_log_sources"))

@log_bp.route("/sources/edit/<int:source_id>", methods=["GET", "POST"])
@login_required
@admin_required
def edit_log_source(source_id):
    source = LogSource.query.get_or_404(source_id)

    if request.method == "POST":
        new_name = request.form["name"]
        new_path = request.form["file_path"]
        enabled = "enabled" in request.form
        reset_offset = "reset_offset" in request.form

        # Detect path change
        path_changed = new_path != source.file_path

        source.name = new_name
        source.file_path = new_path
        source.enabled = enabled

        # Reset offset if requested OR path changed
        if reset_offset or path_changed:
            source.last_read_offset = 0

        db.session.commit()

        flash("Log source updated successfully", "success")
        return redirect(url_for("logs.list_log_sources"))

    return render_template("edit_log_source.html", source=source)


# Admin + User
@log_bp.route("/search", methods=["GET", "POST"])
@login_required
def search_logs():
    results = []

    if request.method == "POST":
        keyword = request.form.get("keyword", "").strip()

        if keyword:
            results = LogEntry.query.filter(
                LogEntry.message.ilike(f"%{keyword}%")
            ).order_by(LogEntry.created_at.desc()).all()

    return render_template("search_logs.html", results=results)

app/templates/partials/header.html
<div class="header">
    <span>Welcome, {{ current_user.username }}</span>
</div>

app/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('auth.dashboard') }}">
      LogWatch
    </a>

    <button class="navbar-toggler" type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">

        <!-- <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.dashboard') }}">
            Dashboard
          </a>
        </li> -->

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('logs.search_logs') }}">
            Search Logs 
          </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('alerts.list_alerts') }}">
                Alerts
            </a>
        </li>


        {% if current_user.role == "admin" %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('logs.list_log_sources') }}">
            Log Sources
          </a>
        </li>
        {% endif %}

      </ul>

      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
             href="#" role="button"
             data-bs-toggle="dropdown">
            {{ current_user.username }}
          </a>

          <ul class="dropdown-menu dropdown-menu-end">
            <li>
              <a class="dropdown-item"
                 href="{{ url_for('auth.logout') }}">
                Logout
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/partials/sidebar.html
<div class="sidebar">
    <h2>LogWatch</h2>

    <a href="{{ url_for('auth.dashboard') }}">Dashboard</a>
    <a href="{{ url_for('logs.list_log_sources') }}">Log Sources</a>
    <a href="{{ url_for('logs.search_logs') }}">Search Logs</a>
    <a href="{{ url_for('alerts.create_alert') }}">Create Alert</a>
    <a href="{{ url_for('history.alert_history') }}">Alert History</a>

    <hr>

    <a href="{{ url_for('auth.logout') }}" class="logout">Logout</a>
</div>